### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by Puumanamana** [dcdanko/minerva_barcode_deconvolution#11]
Hello David,

I just discovered Minerva recently and I want to use it on my dataset. I was able to install it very easily and use it on a subset of my data. I am now trying to run Minerva on my whole 10X dataset (~300M PE reads, ~2.8M barcodes) on a server with 500 GB memory. As mentioned in the readme, I used the following command:
```bash
> cat barcoded.fastq | minerva_deconvolve -k 20 -w 40 -d 8 -a 20 --remove-stopwords --eps 0.51 > ebc_assignments.tsv
```

After running for a few days, the output file was still empty and the last output on stdout was:
"parsed 1,327,100" when it OOM. 

My question is: did you ever used Minerva on a dataset this size? Is there a workaround to limit memory usage on my data? Also, in the paper, you mention that the method is easy to multithread. Is it something I can do on my end (for instance by splitting the fastq file) or something that might be included in Minerva in the future ?

Thank you,
Cédric

**Comment by dcdanko** [comment]
Glad you tried out Minerva, however the issues here don't really surprise me. This is definitely a much bigger dataset than we tested on and we already had performance issues.

A better solution here would be to use [Ariadne](https://github.com/lauren-mak/ariadne) which is the successor to Minerva. It produces better results and it's much more efficient as well.

**Comment by Puumanamana** [comment]
Thank you, I will try it out. Do you have any preprint explaining what approach is taking Ariadne? Or is it just Minerva, but faster ?

**Comment by dcdanko** [comment]
Ariadne uses a different approach than Minerva- rather than looking for kmer overlap it builds a De Bruijn graph and deconvolves barcodes based on that.

It's still under development so no preprint yet but it's certainly already better than Minerva
