### ISSUE TITLE
Only a fraction of reads are deconvolved

### ISSUE THREAD

**Issue by RolandFaure** [dcdanko/minerva_barcode_deconvolution#12]
Hello,

I am trying to run Minerva on a toy dataset, but the output file of Minerva only contains about 1% of all the reads present in my original file. I have lowered the thresholds to -a 1 and -d 1 to exclude as few reads as possible. The command line is

cat ./reads_cov50_redundance4.fastq | minerva_deconvolve -k 20 -w 40 -d 1 -a 1 --remove-stopwords --eps 0.51 > results_minerva/deconvolved_minerva_E_coli.tsv

The problem may come from the way this toy data is generated, which is not identical to the output of longranger basic (the tags are number, not sequence, for example). Here are a few lines of the input fastq:

@read0_TBX:0    BX:Z:4104
AAAGCGAGTCGAACCACTTCCGAAGGAGCCGTTCGCTAATTGTGCACGAGTCTAAGTATGTATCTAGGACCTCTCCCTAAACCTCGATCTCGTGCCTTCGTCTGTCGTCCGATAGGCCTATGGCTACTCAGTTCTATTCTAGACGTCCTG
+
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
@read0_TBX:0    BX:Z:4104
ACTCAGTTAGACAAGAGGTACTTCAGAACCTAAGTGACAACCTTGTCTCTCGAGTGGGAGTACCCCGCCAAGTAAGCCTAGGATGATATGCCTACCAAAGCTACCAACGGGCACGTCATCCTTCTCGGCGCGAGGCCCAACGGGATTATG
+
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
@read1_TBX:0    BX:Z:4104
CGTGGATATGATGAGATCAACCTGAATGTCGGCTGCCCGTCTGACCGGGTGCAGAACGGCATGTTTGGTGCGTGTCTGATGGGTAATGCGCAGCTGGTTGCCGACTGCGTGAAAGCGATGCGCGATGTGGTGTCGATTCCGGTGACGGTG
+
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
@read1_TBX:0    BX:Z:4104
TTTCCGGCAAAGGCGAGTGTGAGATGTTCATCATCCACGCACGTAAAGCCTGGCTTTCGGGGTTAAGCCCGAAAGAAAACCGTGAAATCCCGCCGCTCGATTATCCGCGTGTGTATCAACTGAAGCGTGACTTTCCGCATCTGACGATGT
+
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Do you have any idea of what I should change to have a better result ?

Thanks in advance,
Roland

**Comment by dcdanko** [comment]
That's accurate, Minerva does not deconvolve all the reads in a dataset and the fraction can be quite low for some datasets/parameters.

While we were still able to improve some of our downstream metrics with only a fraction of reads deconvolved I would recommend you use the v2 algorithm [Ariadne](https://github.com/lauren-mak/Ariadne) for any production work you want to do.
