### ISSUE TITLE
division by zero error

### ISSUE THREAD

**Issue by bbsunchen** [dcdanko/minerva_barcode_deconvolution#3]
I keep getting this division by zero error, with different datasets:
```
parsed 966,783 barcodes
Removing 2,518,439 stop and singleton kmers
Removed stop and singleton kmers
686,968 barcodes were at or above dropout threshold

Traceback (most recent call last):
  File "/research/c/anaconda3/bin/minerva_deconvolve", line 11, in <module>
    load_entry_point('minerva-barcoded-read-deconvolution', 'console_scripts', 'minerva_deconvolve')()
  File "/research/c/src/minerva_barcode_deconvolution/minerva/deconvolution/deconvolve_barcodes.py", line 35, in main
    progressBar.write()
  File "/research/c/src/minerva_barcode_deconvolution/minerva/deconvolution/progress_bar.py", line 23, in write
    p = self.events / self.total
ZeroDivisionError: float division by zero
```

**Comment by dcdanko** [comment]
None of your barcodes were large enough to pass the anchor threshold.

This isn't your fault, the anchor threshold was way too high by default. I changed the default and added some logging so this issue is more obvious in future.

you can download the new version or use the '--anchor-dropout' flag

**Comment by bbsunchen** [comment]
Thanks for the quick response, this is the command I used:
`zcat barcoded.fastq.gz | minerva_deconvolve -k 20 -w 40 -d 8 -a 50 --remove-stopwords > ebc_assignments.tsv
`
I've already used the `--anchor-dropout` flag.

**Comment by dcdanko** [comment]
Are you certain you have barcodes with more than 50 read pairs?

If so is your fastq file sorted by barcode?

**Comment by bbsunchen** [comment]
I decrease the `-a` threshold to `20` and it works. Thanks!

**Comment by dcdanko** [comment]
great!
