### ISSUE TITLE
running on provided sample data

### ISSUE THREAD

**Issue by rchikhi** [dcdanko/minerva_barcode_deconvolution#5]
Dear David,

When running the latest github version of Minerva on the sample data from the README (Dataset 1) using parameters recommended from the README (`-k 20 -w 40 -d 8 -a 50 --remove-stopwords`), the program produces no results to `stdout`, and only outputs debug info to `stderr`. This behavior doesn't happen on other test datasets, where proper results are printed to `stdout`. I also tried with `-k 20 -a 50` as per the bioRxiv paper and no luck. What were the parameters used on that dataset?

To reproduce the issue
```
wget https://s3.us-east-2.amazonaws.com/minerva-datasets/10M.data1_atgctgaaq.fq.gz
zcat 10M.data1_atgctgaaq.fq.gz |  minerva_deconvolve -k 20 -w 40 -d 8 -a 50 --remove-stopwords > results.tsv
wc -l results.tsv # returns 0
```

Thanks in advance,
Rayan

**Comment by dcdanko** [comment]
This is an issue with the README, try using `-d 4 -a 4` for the test dataset

**Comment by rchikhi** [comment]
Hi David, thanks for this answer. `-d 4 -a 4` indeed is producing some results to stdout but the run still isn't over after 3 days. Are there any other parameters I should be aware of?

Rayan

**Comment by dcdanko** [comment]
You can increase `-a` which will improve speed by not deconvolving small barcodes but the algorithm is slow. That's the major drawback right now.

**Comment by rchikhi** [comment]
Hi David, Alright, thanks. I will try running it again with larger `-a`. It bothers me a little bit that the parameters for the bioRxiv results aren't known, but maybe things are in flux during journal submission. I look forward to the final version.

Rayan
