### ISSUE TITLE
SyntaxError to install

### ISSUE THREAD

**Issue by WengJianCong** [dcdanko/minerva_barcode_deconvolution#8]
I followed the installation procedure on README, and I can finish installation of requirements using pip(pip verson: 18.1;  python verson: 3.6). But when I install Minerva from the code, it comes up a SyntaxError. The detail SyntaxError seems like: 
![image](https://user-images.githubusercontent.com/34738853/50805019-7ccf6980-132b-11e9-9cc2-10a5bd7c02d2.png)

After installation, the "minerva_annotate" and "minerva_eval" can run successfully. But the "minerva_deconvolve" and "minerva_enhance_kraken" can not be installed successfully. 

Is my installation procedure wrong? I will be very appreciated if you could help me fix it.

**Comment by dcdanko** [comment]
This issue should be solved by PR #7 and PyPi v1.0.1. Please let me know if the issue persists.
